- name: My debug playbook
  hosts: mynodes
  become: false
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
    - name: import a playbook
      ansible.builtin.import_playbook: playbook_name.yml
    - import_playbook: playbook_name.yml
      